apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  # namespace: my-namespace  # Assuming you want to keep the namespace from your previous context
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  - name: app-container
    image: redis:latest  # Using redis:latest as a placeholder
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /data
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/os: linux
    